on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  my_job:
    runs-on: [self-hosted]
    steps:
      - name: echo
        run: |
          sudo docker --version
